# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class PluginTransferPayOutClientApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def plugin_transfer_pay_out_client_plugin_pay_out_post(self, **kwargs):  # noqa: E501
        """plugin_transfer_pay_out_client_plugin_pay_out_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_transfer_pay_out_client_plugin_pay_out_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PluginPayOutPost plugin_pay_out:
        :return: PluginPayOutResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.plugin_transfer_pay_out_client_plugin_pay_out_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.plugin_transfer_pay_out_client_plugin_pay_out_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def plugin_transfer_pay_out_client_plugin_pay_out_post_with_http_info(self, **kwargs):  # noqa: E501
        """plugin_transfer_pay_out_client_plugin_pay_out_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_transfer_pay_out_client_plugin_pay_out_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PluginPayOutPost plugin_pay_out:
        :return: PluginPayOutResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['plugin_pay_out']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method plugin_transfer_pay_out_client_plugin_pay_out_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'plugin_pay_out' in params:
            body_params = params['plugin_pay_out']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json;odata.metadata=minimal;odata.streaming=true', 'application/json;odata.metadata=minimal;odata.streaming=false', 'application/json;odata.metadata=minimal', 'application/json;odata.metadata=full;odata.streaming=true', 'application/json;odata.metadata=full;odata.streaming=false', 'application/json;odata.metadata=full', 'application/json;odata.metadata=none;odata.streaming=true', 'application/json;odata.metadata=none;odata.streaming=false', 'application/json;odata.metadata=none', 'application/json;odata.streaming=true', 'application/json;odata.streaming=false', 'application/json', 'application/xml', 'application/prs.odatatestxx-odata', 'text/plain', 'text/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json;odata.metadata=minimal;odata.streaming=true', 'application/json;odata.metadata=minimal;odata.streaming=false', 'application/json;odata.metadata=minimal', 'application/json;odata.metadata=full;odata.streaming=true', 'application/json;odata.metadata=full;odata.streaming=false', 'application/json;odata.metadata=full', 'application/json;odata.metadata=none;odata.streaming=true', 'application/json;odata.metadata=none;odata.streaming=false', 'application/json;odata.metadata=none', 'application/json;odata.streaming=true', 'application/json;odata.streaming=false', 'application/json', 'application/xml', 'application/prs.odatatestxx-odata', 'application/json;odata.metadata=minimal;odata.streaming=true', 'application/json;odata.metadata=minimal;odata.streaming=false', 'application/json;odata.metadata=minimal', 'application/json;odata.metadata=full;odata.streaming=true', 'application/json;odata.metadata=full;odata.streaming=false', 'application/json;odata.metadata=full', 'application/json;odata.metadata=none;odata.streaming=true', 'application/json;odata.metadata=none;odata.streaming=false', 'application/json;odata.metadata=none', 'application/json;odata.streaming=true', 'application/json;odata.streaming=false', 'application/json', 'application/xml', 'application/prs.odatatestxx-odata', 'application/json-patch+json', 'application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/v2.1/PayOutsPlugin', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PluginPayOutResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def plugin_transfer_pay_out_client_pluging_get_pay_out(self, pay_out_id, **kwargs):  # noqa: E501
        """plugin_transfer_pay_out_client_pluging_get_pay_out  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_transfer_pay_out_client_pluging_get_pay_out(pay_out_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int pay_out_id: (required)
        :return: PluginPayOutResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.plugin_transfer_pay_out_client_pluging_get_pay_out_with_http_info(pay_out_id, **kwargs)  # noqa: E501
        else:
            (data) = self.plugin_transfer_pay_out_client_pluging_get_pay_out_with_http_info(pay_out_id, **kwargs)  # noqa: E501
            return data

    def plugin_transfer_pay_out_client_pluging_get_pay_out_with_http_info(self, pay_out_id, **kwargs):  # noqa: E501
        """plugin_transfer_pay_out_client_pluging_get_pay_out  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.plugin_transfer_pay_out_client_pluging_get_pay_out_with_http_info(pay_out_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int pay_out_id: (required)
        :return: PluginPayOutResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['pay_out_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method plugin_transfer_pay_out_client_pluging_get_pay_out" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'pay_out_id' is set
        if ('pay_out_id' not in params or
                params['pay_out_id'] is None):
            raise ValueError("Missing the required parameter `pay_out_id` when calling `plugin_transfer_pay_out_client_pluging_get_pay_out`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'pay_out_id' in params:
            path_params['payOutId'] = params['pay_out_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json;odata.metadata=minimal;odata.streaming=true', 'application/json;odata.metadata=minimal;odata.streaming=false', 'application/json;odata.metadata=minimal', 'application/json;odata.metadata=full;odata.streaming=true', 'application/json;odata.metadata=full;odata.streaming=false', 'application/json;odata.metadata=full', 'application/json;odata.metadata=none;odata.streaming=true', 'application/json;odata.metadata=none;odata.streaming=false', 'application/json;odata.metadata=none', 'application/json;odata.streaming=true', 'application/json;odata.streaming=false', 'application/json', 'application/xml', 'application/prs.odatatestxx-odata', 'text/plain', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth2']  # noqa: E501

        return self.api_client.call_api(
            '/v2.1/PayOutsPlugin/{PayOutId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PluginPayOutResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
