# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.money import Money  # noqa: F401,E501


class AddonPaymentsPayDirectPost(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tag': 'str',
        'card_id': 'str',
        'credited_wallet_id': 'str',
        'statement_descriptor': 'str',
        'debited_funds': 'Money',
        'fees': 'Money',
        'language': 'str'
    }

    attribute_map = {
        'tag': 'Tag',
        'card_id': 'CardId',
        'credited_wallet_id': 'CreditedWalletId',
        'statement_descriptor': 'StatementDescriptor',
        'debited_funds': 'DebitedFunds',
        'fees': 'Fees',
        'language': 'Language'
    }

    def __init__(self, tag=None, card_id=None, credited_wallet_id=None, statement_descriptor=None, debited_funds=None, fees=None, language=None):  # noqa: E501
        """AddonPaymentsPayDirectPost - a model defined in Swagger"""  # noqa: E501

        self._tag = None
        self._card_id = None
        self._credited_wallet_id = None
        self._statement_descriptor = None
        self._debited_funds = None
        self._fees = None
        self._language = None
        self.discriminator = None

        if tag is not None:
            self.tag = tag
        self.card_id = card_id
        self.credited_wallet_id = credited_wallet_id
        if statement_descriptor is not None:
            self.statement_descriptor = statement_descriptor
        self.debited_funds = debited_funds
        self.fees = fees
        if language is not None:
            self.language = language

    @property
    def tag(self):
        """Gets the tag of this AddonPaymentsPayDirectPost.  # noqa: E501


        :return: The tag of this AddonPaymentsPayDirectPost.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this AddonPaymentsPayDirectPost.


        :param tag: The tag of this AddonPaymentsPayDirectPost.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def card_id(self):
        """Gets the card_id of this AddonPaymentsPayDirectPost.  # noqa: E501


        :return: The card_id of this AddonPaymentsPayDirectPost.  # noqa: E501
        :rtype: str
        """
        return self._card_id

    @card_id.setter
    def card_id(self, card_id):
        """Sets the card_id of this AddonPaymentsPayDirectPost.


        :param card_id: The card_id of this AddonPaymentsPayDirectPost.  # noqa: E501
        :type: str
        """
        if card_id is None:
            raise ValueError("Invalid value for `card_id`, must not be `None`")  # noqa: E501

        self._card_id = card_id

    @property
    def credited_wallet_id(self):
        """Gets the credited_wallet_id of this AddonPaymentsPayDirectPost.  # noqa: E501


        :return: The credited_wallet_id of this AddonPaymentsPayDirectPost.  # noqa: E501
        :rtype: str
        """
        return self._credited_wallet_id

    @credited_wallet_id.setter
    def credited_wallet_id(self, credited_wallet_id):
        """Sets the credited_wallet_id of this AddonPaymentsPayDirectPost.


        :param credited_wallet_id: The credited_wallet_id of this AddonPaymentsPayDirectPost.  # noqa: E501
        :type: str
        """
        if credited_wallet_id is None:
            raise ValueError("Invalid value for `credited_wallet_id`, must not be `None`")  # noqa: E501

        self._credited_wallet_id = credited_wallet_id

    @property
    def statement_descriptor(self):
        """Gets the statement_descriptor of this AddonPaymentsPayDirectPost.  # noqa: E501


        :return: The statement_descriptor of this AddonPaymentsPayDirectPost.  # noqa: E501
        :rtype: str
        """
        return self._statement_descriptor

    @statement_descriptor.setter
    def statement_descriptor(self, statement_descriptor):
        """Sets the statement_descriptor of this AddonPaymentsPayDirectPost.


        :param statement_descriptor: The statement_descriptor of this AddonPaymentsPayDirectPost.  # noqa: E501
        :type: str
        """

        self._statement_descriptor = statement_descriptor

    @property
    def debited_funds(self):
        """Gets the debited_funds of this AddonPaymentsPayDirectPost.  # noqa: E501


        :return: The debited_funds of this AddonPaymentsPayDirectPost.  # noqa: E501
        :rtype: Money
        """
        return self._debited_funds

    @debited_funds.setter
    def debited_funds(self, debited_funds):
        """Sets the debited_funds of this AddonPaymentsPayDirectPost.


        :param debited_funds: The debited_funds of this AddonPaymentsPayDirectPost.  # noqa: E501
        :type: Money
        """
        if debited_funds is None:
            raise ValueError("Invalid value for `debited_funds`, must not be `None`")  # noqa: E501

        self._debited_funds = debited_funds

    @property
    def fees(self):
        """Gets the fees of this AddonPaymentsPayDirectPost.  # noqa: E501


        :return: The fees of this AddonPaymentsPayDirectPost.  # noqa: E501
        :rtype: Money
        """
        return self._fees

    @fees.setter
    def fees(self, fees):
        """Sets the fees of this AddonPaymentsPayDirectPost.


        :param fees: The fees of this AddonPaymentsPayDirectPost.  # noqa: E501
        :type: Money
        """
        if fees is None:
            raise ValueError("Invalid value for `fees`, must not be `None`")  # noqa: E501

        self._fees = fees

    @property
    def language(self):
        """Gets the language of this AddonPaymentsPayDirectPost.  # noqa: E501


        :return: The language of this AddonPaymentsPayDirectPost.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this AddonPaymentsPayDirectPost.


        :param language: The language of this AddonPaymentsPayDirectPost.  # noqa: E501
        :type: str
        """
        allowed_values = ["NotSpecified", "CA", "DE", "EN", "DA", "ES", "ET", "GL", "FI", "FR", "EL", "EU", "HU", "IT", "NL", "NO", "PL", "PT", "SK", "SV", "CS"]  # noqa: E501
        if language not in allowed_values:
            raise ValueError(
                "Invalid value for `language` ({0}), must be one of {1}"  # noqa: E501
                .format(language, allowed_values)
            )

        self._language = language

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddonPaymentsPayDirectPost, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddonPaymentsPayDirectPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
