# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.money import Money  # noqa: F401,E501


class WebPayPayByWebPost(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'debited_funds': 'Money',
        'fees': 'Money',
        'card_id': 'str',
        'statement_descriptor': 'str',
        'tag': 'str',
        'credited_wallet_id': 'str',
        'success_url': 'str',
        'cancel_url': 'str'
    }

    attribute_map = {
        'debited_funds': 'DebitedFunds',
        'fees': 'Fees',
        'card_id': 'CardId',
        'statement_descriptor': 'StatementDescriptor',
        'tag': 'Tag',
        'credited_wallet_id': 'CreditedWalletId',
        'success_url': 'SuccessUrl',
        'cancel_url': 'CancelUrl'
    }

    def __init__(self, debited_funds=None, fees=None, card_id=None, statement_descriptor=None, tag=None, credited_wallet_id=None, success_url=None, cancel_url=None):  # noqa: E501
        """WebPayPayByWebPost - a model defined in Swagger"""  # noqa: E501

        self._debited_funds = None
        self._fees = None
        self._card_id = None
        self._statement_descriptor = None
        self._tag = None
        self._credited_wallet_id = None
        self._success_url = None
        self._cancel_url = None
        self.discriminator = None

        self.debited_funds = debited_funds
        self.fees = fees
        if card_id is not None:
            self.card_id = card_id
        self.statement_descriptor = statement_descriptor
        if tag is not None:
            self.tag = tag
        self.credited_wallet_id = credited_wallet_id
        if success_url is not None:
            self.success_url = success_url
        if cancel_url is not None:
            self.cancel_url = cancel_url

    @property
    def debited_funds(self):
        """Gets the debited_funds of this WebPayPayByWebPost.  # noqa: E501


        :return: The debited_funds of this WebPayPayByWebPost.  # noqa: E501
        :rtype: Money
        """
        return self._debited_funds

    @debited_funds.setter
    def debited_funds(self, debited_funds):
        """Sets the debited_funds of this WebPayPayByWebPost.


        :param debited_funds: The debited_funds of this WebPayPayByWebPost.  # noqa: E501
        :type: Money
        """
        if debited_funds is None:
            raise ValueError("Invalid value for `debited_funds`, must not be `None`")  # noqa: E501

        self._debited_funds = debited_funds

    @property
    def fees(self):
        """Gets the fees of this WebPayPayByWebPost.  # noqa: E501


        :return: The fees of this WebPayPayByWebPost.  # noqa: E501
        :rtype: Money
        """
        return self._fees

    @fees.setter
    def fees(self, fees):
        """Sets the fees of this WebPayPayByWebPost.


        :param fees: The fees of this WebPayPayByWebPost.  # noqa: E501
        :type: Money
        """
        if fees is None:
            raise ValueError("Invalid value for `fees`, must not be `None`")  # noqa: E501

        self._fees = fees

    @property
    def card_id(self):
        """Gets the card_id of this WebPayPayByWebPost.  # noqa: E501


        :return: The card_id of this WebPayPayByWebPost.  # noqa: E501
        :rtype: str
        """
        return self._card_id

    @card_id.setter
    def card_id(self, card_id):
        """Sets the card_id of this WebPayPayByWebPost.


        :param card_id: The card_id of this WebPayPayByWebPost.  # noqa: E501
        :type: str
        """

        self._card_id = card_id

    @property
    def statement_descriptor(self):
        """Gets the statement_descriptor of this WebPayPayByWebPost.  # noqa: E501


        :return: The statement_descriptor of this WebPayPayByWebPost.  # noqa: E501
        :rtype: str
        """
        return self._statement_descriptor

    @statement_descriptor.setter
    def statement_descriptor(self, statement_descriptor):
        """Sets the statement_descriptor of this WebPayPayByWebPost.


        :param statement_descriptor: The statement_descriptor of this WebPayPayByWebPost.  # noqa: E501
        :type: str
        """
        if statement_descriptor is None:
            raise ValueError("Invalid value for `statement_descriptor`, must not be `None`")  # noqa: E501

        self._statement_descriptor = statement_descriptor

    @property
    def tag(self):
        """Gets the tag of this WebPayPayByWebPost.  # noqa: E501


        :return: The tag of this WebPayPayByWebPost.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this WebPayPayByWebPost.


        :param tag: The tag of this WebPayPayByWebPost.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def credited_wallet_id(self):
        """Gets the credited_wallet_id of this WebPayPayByWebPost.  # noqa: E501


        :return: The credited_wallet_id of this WebPayPayByWebPost.  # noqa: E501
        :rtype: str
        """
        return self._credited_wallet_id

    @credited_wallet_id.setter
    def credited_wallet_id(self, credited_wallet_id):
        """Sets the credited_wallet_id of this WebPayPayByWebPost.


        :param credited_wallet_id: The credited_wallet_id of this WebPayPayByWebPost.  # noqa: E501
        :type: str
        """
        if credited_wallet_id is None:
            raise ValueError("Invalid value for `credited_wallet_id`, must not be `None`")  # noqa: E501

        self._credited_wallet_id = credited_wallet_id

    @property
    def success_url(self):
        """Gets the success_url of this WebPayPayByWebPost.  # noqa: E501


        :return: The success_url of this WebPayPayByWebPost.  # noqa: E501
        :rtype: str
        """
        return self._success_url

    @success_url.setter
    def success_url(self, success_url):
        """Sets the success_url of this WebPayPayByWebPost.


        :param success_url: The success_url of this WebPayPayByWebPost.  # noqa: E501
        :type: str
        """

        self._success_url = success_url

    @property
    def cancel_url(self):
        """Gets the cancel_url of this WebPayPayByWebPost.  # noqa: E501


        :return: The cancel_url of this WebPayPayByWebPost.  # noqa: E501
        :rtype: str
        """
        return self._cancel_url

    @cancel_url.setter
    def cancel_url(self, cancel_url):
        """Sets the cancel_url of this WebPayPayByWebPost.


        :param cancel_url: The cancel_url of this WebPayPayByWebPost.  # noqa: E501
        :type: str
        """

        self._cancel_url = cancel_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebPayPayByWebPost, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebPayPayByWebPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
