# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class WebPayTokenRequestPost(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success_url': 'str',
        'cancel_url': 'str',
        'tag': 'str',
        'credited_wallet_id': 'str'
    }

    attribute_map = {
        'success_url': 'SuccessUrl',
        'cancel_url': 'CancelUrl',
        'tag': 'Tag',
        'credited_wallet_id': 'CreditedWalletId'
    }

    def __init__(self, success_url=None, cancel_url=None, tag=None, credited_wallet_id=None):  # noqa: E501
        """WebPayTokenRequestPost - a model defined in Swagger"""  # noqa: E501

        self._success_url = None
        self._cancel_url = None
        self._tag = None
        self._credited_wallet_id = None
        self.discriminator = None

        if success_url is not None:
            self.success_url = success_url
        if cancel_url is not None:
            self.cancel_url = cancel_url
        if tag is not None:
            self.tag = tag
        self.credited_wallet_id = credited_wallet_id

    @property
    def success_url(self):
        """Gets the success_url of this WebPayTokenRequestPost.  # noqa: E501


        :return: The success_url of this WebPayTokenRequestPost.  # noqa: E501
        :rtype: str
        """
        return self._success_url

    @success_url.setter
    def success_url(self, success_url):
        """Sets the success_url of this WebPayTokenRequestPost.


        :param success_url: The success_url of this WebPayTokenRequestPost.  # noqa: E501
        :type: str
        """

        self._success_url = success_url

    @property
    def cancel_url(self):
        """Gets the cancel_url of this WebPayTokenRequestPost.  # noqa: E501


        :return: The cancel_url of this WebPayTokenRequestPost.  # noqa: E501
        :rtype: str
        """
        return self._cancel_url

    @cancel_url.setter
    def cancel_url(self, cancel_url):
        """Sets the cancel_url of this WebPayTokenRequestPost.


        :param cancel_url: The cancel_url of this WebPayTokenRequestPost.  # noqa: E501
        :type: str
        """

        self._cancel_url = cancel_url

    @property
    def tag(self):
        """Gets the tag of this WebPayTokenRequestPost.  # noqa: E501


        :return: The tag of this WebPayTokenRequestPost.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this WebPayTokenRequestPost.


        :param tag: The tag of this WebPayTokenRequestPost.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def credited_wallet_id(self):
        """Gets the credited_wallet_id of this WebPayTokenRequestPost.  # noqa: E501


        :return: The credited_wallet_id of this WebPayTokenRequestPost.  # noqa: E501
        :rtype: str
        """
        return self._credited_wallet_id

    @credited_wallet_id.setter
    def credited_wallet_id(self, credited_wallet_id):
        """Sets the credited_wallet_id of this WebPayTokenRequestPost.


        :param credited_wallet_id: The credited_wallet_id of this WebPayTokenRequestPost.  # noqa: E501
        :type: str
        """
        if credited_wallet_id is None:
            raise ValueError("Invalid value for `credited_wallet_id`, must not be `None`")  # noqa: E501

        self._credited_wallet_id = credited_wallet_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebPayTokenRequestPost, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebPayTokenRequestPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
