# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pay_in_bankwire_response import PayInBankwireResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestPayInBankwireResponse(unittest.TestCase):
    """PayInBankwireResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayInBankwireResponse(self):
        """Test PayInBankwireResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pay_in_bankwire_response.PayInBankwireResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
