# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transfers_api import TransfersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransfersApi(unittest.TestCase):
    """TransfersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.transfers_api.TransfersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_transfers_get(self):
        """Test case for transfers_get

        """
        pass

    def test_transfers_get_list(self):
        """Test case for transfers_get_list

        """
        pass

    def test_transfers_post(self):
        """Test case for transfers_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
