# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.wallet_put import WalletPut  # noqa: E501
from swagger_client.rest import ApiException


class TestWalletPut(unittest.TestCase):
    """WalletPut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWalletPut(self):
        """Test WalletPut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.wallet_put.WalletPut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
