# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.pay_ins_web_pay_api import PayInsWebPayApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPayInsWebPayApi(unittest.TestCase):
    """PayInsWebPayApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.pay_ins_web_pay_api.PayInsWebPayApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pay_ins_web_pay_delete_web_pay_token(self):
        """Test case for pay_ins_web_pay_delete_web_pay_token

        """
        pass

    def test_pay_ins_web_pay_get_web_pay_tokenization(self):
        """Test case for pay_ins_web_pay_get_web_pay_tokenization

        """
        pass

    def test_pay_ins_web_pay_web_pay_get_payment(self):
        """Test case for pay_ins_web_pay_web_pay_get_payment

        """
        pass

    def test_pay_ins_web_pay_web_pay_post_payment_by_web(self):
        """Test case for pay_ins_web_pay_web_pay_post_payment_by_web

        """
        pass

    def test_pay_ins_web_pay_web_pay_post_refund(self):
        """Test case for pay_ins_web_pay_web_pay_post_refund

        """
        pass

    def test_pay_ins_web_pay_web_pay_save_card(self):
        """Test case for pay_ins_web_pay_web_pay_save_card

        """
        pass


if __name__ == '__main__':
    unittest.main()
