# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.response_list_kyc_user_validation_level_legal_response import ResponseListKycUserValidationLevelLegalResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestResponseListKycUserValidationLevelLegalResponse(unittest.TestCase):
    """ResponseListKycUserValidationLevelLegalResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseListKycUserValidationLevelLegalResponse(self):
        """Test ResponseListKycUserValidationLevelLegalResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.response_list_kyc_user_validation_level_legal_response.ResponseListKycUserValidationLevelLegalResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
