# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.me_api import MeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMeApi(unittest.TestCase):
    """MeApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.me_api.MeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_me_get(self):
        """Test case for me_get

        """
        pass

    def test_me_get_list(self):
        """Test case for me_get_list

        """
        pass

    def test_me_get_pay_ins(self):
        """Test case for me_get_pay_ins

        """
        pass


if __name__ == '__main__':
    unittest.main()
