# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.web_pay_tokenize_by_web_response import WebPayTokenizeByWebResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestWebPayTokenizeByWebResponse(unittest.TestCase):
    """WebPayTokenizeByWebResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebPayTokenizeByWebResponse(self):
        """Test WebPayTokenizeByWebResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.web_pay_tokenize_by_web_response.WebPayTokenizeByWebResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
