# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cards_api import CardsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCardsApi(unittest.TestCase):
    """CardsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cards_api.CardsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cards_get(self):
        """Test case for cards_get

        View a Card  # noqa: E501
        """
        pass

    def test_cards_get_list(self):
        """Test case for cards_get_list

        """
        pass

    def test_cards_put(self):
        """Test case for cards_put

        Deactivate a Card  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
