# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.wallet_query_balances_by_ids_post import WalletQueryBalancesByIdsPost  # noqa: E501
from swagger_client.rest import ApiException


class TestWalletQueryBalancesByIdsPost(unittest.TestCase):
    """WalletQueryBalancesByIdsPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWalletQueryBalancesByIdsPost(self):
        """Test WalletQueryBalancesByIdsPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.wallet_query_balances_by_ids_post.WalletQueryBalancesByIdsPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
