# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.kyc_identification_request import KycIdentificationRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestKycIdentificationRequest(unittest.TestCase):
    """KycIdentificationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKycIdentificationRequest(self):
        """Test KycIdentificationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.kyc_identification_request.KycIdentificationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
