# coding: utf-8

"""
    MarketPay API

    API for Smart Contracts and Payments  # noqa: E501

    OpenAPI spec version: v2.01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.response_list_wallet_client_instrument_response import ResponseListWalletClientInstrumentResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestResponseListWalletClientInstrumentResponse(unittest.TestCase):
    """ResponseListWalletClientInstrumentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseListWalletClientInstrumentResponse(self):
        """Test ResponseListWalletClientInstrumentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.response_list_wallet_client_instrument_response.ResponseListWalletClientInstrumentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
